@startuml 商品管理システムドメインモデル（簡略版）
skinparam componentStyle rectangle

' =====================
' 販売システム
' =====================
[ユーザー] o-- [支払情報]
[ユーザー] o-- [カート]
[カート] o-- [商品]

[ユーザー] --> [カート]
[ユーザー] --> [支払情報]
[ユーザー] --> [注文]

' =====================
' 管理システム
' =====================
[管理者] o-- [決済履歴]
[管理者] --> [ユーザー]
[管理者] --> [管理履歴]

' =====================
' 共通システム
' =====================
[商品] o-- [カテゴリ]

[注文] o-- [注文詳細]
[注文] o-- [発送]
[注文詳細] o-- [商品]
[発送] o-- [配送業者]

[返品] o-- [注文]
[返品] o-- [注文詳細]
[返品] o-- [返金]
[返金] o-- [決済履歴]

@enduml
