@startuml 倉庫・出荷管理システム_統合シーケンス図_V2_メソッド修正
hide footbox
' スタイル設定
skinparam boundaryBackgroundColor #D5E8D4
skinparam controlBackgroundColor #F8CECC
skinparam entityBackgroundColor #DAE8FC

' オブジェクト定義 (DFDより)
actor 倉庫担当者 as Staff
boundary 出荷指示管理一覧 as ListScreen
boundary 出荷指示詳細画面 as DetailScreen
control 出荷指示制御 as Control
boundary メッセージ表示画面 as MessageScreen
entity 出荷指示DB as SiDB
entity ピッキングDB as PickingDB
entity 出荷準備ステータスDB as StatusDB
entity 配送システム as DeliverySystem

' 1. 倉庫担当者が一覧画面を操作し、データ取得
Staff -> ListScreen: 出荷指示管理一覧を表示
activate ListScreen
ListScreen -> Control: 指示データ取得要求()
activate Control
Control -> SiDB: 全指示データ要求()
activate SiDB
SiDB --> Control: 指示データ一覧
deactivate SiDB
Control --> ListScreen: 指示データ一覧
deactivate Control

' 2. 倉庫担当者の操作分岐
alt 出荷対象の選択と配送依頼 (詳細情報要求を追加)
    Staff -> ListScreen: **出荷対象を選択 (ID指定)**
    ListScreen -> Control: **詳細データ要求(ID)**
    activate Control

'【追加・修正箇所】詳細データの取得
    Control -> SiDB: **対象IDの指示詳細データを取得()**
    activate SiDB
    SiDB --> Control: **指示詳細データ**
    deactivate SiDB

' DFDのメッセージ「出荷対象の選択要求」に相当する処理
    Control -> DetailScreen: 出荷指示詳細画面を表示
    activate DetailScreen
    DetailScreen -> Staff: **詳細データ表示**
    
  ' DFDのメッセージ「配送依頼を送信」に相当する処理
    Control -> DeliverySystem: 配送依頼を送信()
    activate DeliverySystem
    DeliverySystem --> Control: 配送依頼受付完了メッセージ
    deactivate DeliverySystem
      Control --> ListScreen: 選択完了通知
    deactivate Control
    ListScreen -> Staff: 一覧表示を更新 (または詳細画面へ遷移)
    
else ピッキング完了の登録 (DFD中央下部フロー)
    Staff -> DetailScreen: ピッキング完了ボタン押下
    activate DetailScreen
    DetailScreen -> Control: ピッキング完了の登録()
    activate Control
    
'データベースの更      Control -> StatusDB: 出荷準備ステータスを完了に更新()
    activate StatusDB
    StatusDB --> Control: 更新完了
    deactivate StatusDB
    
    Control -> PickingDB: 完了登録データ送信()
    activate PickingDB
    PickingDB --> Control: 登録完了
    deactivate PickingDB
    
'完了メッセージの表示
    Control -> MessageScreen: 出荷準備完了メッセージを表示
    activate MessageScreen
    MessageScreen --> Control: 表示通知
    deactivate MessageScreen
    
    Control --> DetailScreen: 処理完了
    deactivate Control
    DetailScreen -> Staff: 完了メッセージを表示
    
else 該当指示なしのエラー表示 (DFD中央下部エラーフロー)
    Staff -> DetailScreen: (存在しない)出荷指示の詳細要求
    activate DetailScreen
    DetailScreen -> Control: 指示データ確認要求()
    activate Control
    
    Note over Control: DB検索の結果、指示データなし
    Control -> MessageScreen: 出荷指示がありませんと表示
    activate MessageScreen
    MessageScreen --> Control: 表示通知
    deactivate MessageScreen
    
    Control --> DetailScreen: メッセージ表示指示
    deactivate Control
    DetailScreen -> Staff: 「出荷指示がありません」を表示
end

deactivate DetailScreen
deactivate ListScreen

@end   