@startuml Web_Visitorクラス図
skinparam classAttributeIconSize 0
hide circle

class Web_Visitor {
-訪問者
-ユーザーID
-パスワード
-名前
-学校名
-所属名
-メールアドレス
-電話番号
-年齢

 +ログインする()
 +ログアウトする()
 +自分の情報を登録する()
 +自分と他の訪問者の情報を参照する()
 +自分の情報を変更する()
 +自分の情報を削除する()
}

@enduml


