@startuml Web_Visitorドメインモデル図
skinparam componentStyle rectangle

' Web_Visitor
[訪問者] <|-- [ユーザーID]
[訪問者] <|--  [パスワード]
[訪問者] <|--  [名前]
[訪問者] <|--  [学校名]
[訪問者] <|--  [所属名]
[訪問者] <|--  [メールアドレス]
[訪問者] <|--  [電話番号]
[訪問者] <|--  [年齢]

@enduml