@startuml
skinparam classAttributeIconSize 0
hide circle

' --- 会員クラス ---
class 会員 {
    - 氏名
    -会員番号
    -学生証/職員証
    -メールアドレス
    -貸出上限冊数
    -貸出期間

    +貸出履歴を確認する()
    +予約する()
    +図書を借りる()
    +図書を返す()
}

' --- 事務職員クラス ---
class 事務職員 {
    -氏名
    -事務職員番号

    +貸出処理する()
    +返却処理する()
    +予約管理する()
}

' --- 図書クラス ---
class 図書 {
    -管理番号
    -書名
    -雑誌
    -書籍
}

' --- 貸出履歴クラス ---
class 貸出履歴 {
    -貸出日
    -返却日

    +履歴を参照する()
}

' --- 貸出予約クラス ---
class 貸出予約 {
    -予約日
    -連絡メール

    +予約する()
    +取り置きする()
    +連絡する()
}

@enduml
