@startuml 図書館ドメインモデル
skinparam componentStyle rectangle

[会員] <|-- [学生]
[会員] <|-- [教職員]
[会員] o-- [会員番号]


[会員] o-- [貸出履歴]
[会員] o-- [貸出予約]

[貸出履歴] o-- [図書]
[貸出予約] o-- [図書]

[図書] <|-- [書籍]
[図書] <|-- [雑誌]
[図書] o-- [管理番号]
[図書] o-- [書名]


[貸出履歴] o-- [貸出期間]

[貸出予約] o-- [予約日]
[貸出予約] o-- [連絡メール]

[会員] o-- [学生証/職員証]
[会員] o-- [メールアドレス]

[事務職員] o-- [貸出履歴]
[事務職員] o-- [貸出予約]
[事務職員] o-- [図書]


' 制約

@enduml