@startuml 図書館ドメインモデル図（事務職員向け）
skinparam componentStyle rectangle

' --- 中心となる役割 ---
[事務職員]

' --- 会員関連 ---
[利用者]
[会員]
[学生]
[教職員]

[利用者] <|-- [会員]
[会員] <|-- [学生]
[会員] <|-- [教職員]

[会員] o-- [学生証]
[会員] o-- [職員証]
[会員] o-- [会員番号]
[会員] o-- [貸出履歴]
[会員] o-- [予約カード]
[会員] o-- [貸出上限冊数]
[会員] o-- [貸出期間]

' --- 図書関連 ---
[図書]
[書籍]
[雑誌]

[図書] <|-- [書籍]
[図書] <|-- [雑誌]

[図書] o-- [管理番号]
[図書] o-- [書名]

' --- 貸出・予約管理 ---
[貸出履歴] o-- [貸出]
[貸出] o-- [図書]
[貸出] o-- [返却]

[予約カード] o-- [図書]

' --- 事務職員との関係 ---
[事務職員] o-- [会員] : 登録・管理
[事務職員] o-- [図書] : 管理
[事務職員] o-- [貸出] : 手続き
[事務職員] o-- [予約カード] : 管理
[事務職員] o-- [メール] : 通知

@enduml
