@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle
 
class RoboDog {
-myName: String
'datetime型でいいのでは？
-myTime: int
-goodMorning: String
-goodAfternoon: String
-goodEvening: String
-firstValue: int
-secondvValue: int

'教科書に記載なし
-result: int
 
+getMyName(): String
+setMyName(): int
+setNewTime(): void
+getMyGreeting(): String

'教科書に記載なし
+setTwoValues(): void
+setAndGetResult(): int
}
 
@enduml