@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle
 
class RoboDog {
-myName
-myTime
-goodMorning
-goodAfternoon
-goodEvening
-firstValue
-secondvValue

'教科書に記載なし
-result
 
+getMyName()
+setMyName()
+setNewTime()
+getMyGreeting()

'教科書に記載なし
+setTwoValues()
+setAndGetResult()
}
 
@enduml